version: '3.1'

services:
  mariadb:
    image: mariadb:10.1.25
    ports:
      - 3306:3306
    volumes:
      - ./volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_PASSWORD=${USER_PASSWORD}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
    networks:
      db:

networks:
    db:
        driver: bridge